set(OLD_BUILD_SHARED_LIBS ${BUILD_SHARED_LIBS})
set(BUILD_SHARED_LIBS
    OFF
    CACHE BOOL "" FORCE
)
set(ASSIMP_BUILD_ASSIMP_TOOLS
    OFF
    CACHE BOOL "" FORCE
)
set(ASSIMP_BUILD_TESTS
    OFF
    CACHE BOOL "" FORCE
)
add_subdirectory(extern/assimp)
set(BUILD_SHARED_LIBS
    ${OLD_BUILD_SHARED_LIBS}
    CACHE BOOL "" FORCE
)
